Add SQLModelGenerator
agronholm/sqlacodegen pull request #194
Opened 2022-04-21 09:43 UTC by KhirilovA

## What?
I wrote another generator class that generates SQLModels, and saved a forcepk option ;)
## How?
I stayed with my idea to force primary key for the tables that don't have it, but only if you optional for DeclarativeGenerator and mandatory for SQLModelGenerator.

Based on DeclarativeGenerator i wrote a generator for SQLModels.
Columns are described with sa_column parameter

I didn't implement many-to-many relationships yet.

![Screenshot_2](https://user-images.githubusercontent.com/56589006/164427509-208b7b54-d6b9-40e7-a1a1-149eb6ad4dfd.png)

2022-04-21 09:59 UTC, agronholm commented
I'm inclined to merge support for SQLModel, but I still don't feel comfortable with forcing primary keys.

By the way, I suggest you install the pre-commit git hook to prevent pre-commit.ci checks from failing here.

2022-04-21 10:46 UTC, KhirilovA commented
I removed "forcepk" option from here and fixed pre-commit.ci checks from failing

2022-04-21 11:02 UTC, agronholm commented
I will require new tests that cover this added functionality. When those tests are passing I will merge this.

2022-04-21 11:16 UTC, KhirilovA commented
Ok, should i particapate in it?

2022-04-21 11:22 UTC, agronholm commented
Any new feature needs to accompanied with tests, and yes, the author of said feature needs to add the tests.

2022-04-22 14:36 UTC, KhirilovA commented
I added tests for checking index, constraint generation, one-to-one and one-to-many relationships

2022-04-23 19:55 UTC, agronholm requested changes
Looks promising, just need some code style adjustments.

2022-04-23 19:55 UTC, agronholm commented on src/sqlacodegen/generators.py
> +            if model.relationships:
Please add a blank line after each control block when more code follows on the same indentation level (e.g. to distinguish if...else blocks from unrelated code).
```suggestion

            if model.relationships:
```

2022-04-23 19:55 UTC, agronholm commented on src/sqlacodegen/generators.py
> +        return "\n".join(declarations)
Same as above. There are multiple such cases here, please change them all.
```suggestion

        return "\n".join(declarations)
```

2022-04-23 19:55 UTC, agronholm commented on tests/test_generators.py
> +            """\
Indent these text blocks the same way they're indented in existing code.

2022-04-24 14:44 UTC, agronholm commented on src/sqlacodegen/generators.py
> +            python_type_name = "Any"
This needs the UUID column type hack from the dataclass generator.

2022-04-24 15:02 UTC, agronholm commented
I suggest running the test suite locally using `tox` to determine if the changes you've made actually fix the test failures.

2022-04-24 15:07 UTC, agronholm approved these changes

2022-04-24 15:07 UTC, merged

2022-04-24 15:07 UTC, agronholm commented
Thanks!

2022-04-24 15:10 UTC, KhirilovA commented
Thank you for advices too!

2022-04-25 15:57 UTC, amacfie commented
Cool. SQLModel is an available generator now? Should the README mention it?

2022-04-25 15:59 UTC, agronholm commented
Yes, I have other documentation updates to make too before the next pre-release.