Add support for SQLAlchemy 2.0, continued
agronholm/sqlacodegen pull request #275
Opened 2023-08-02 10:56 UTC by mhauru

Continued from #249, see discussion there.

2023-08-02 10:58 UTC, agronholm commented
Thanks, I'll check this out later today.

2023-08-02 17:54 UTC, agronholm requested changes
I think the code is good enough for merging. I'll do some tinkering on it later.
Aside from the suggestions I've added, I will still need an added changelog entry (remember to give credit to yourself and the author of the original PR).

2023-08-03 09:42 UTC, mhauru commented on .github/workflows/test.yml
>          python-version: ${{ matrix.python-version }}
Done

2023-08-03 09:42 UTC, mhauru commented on .github/workflows/test.yml
> +        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
Done

2023-08-03 09:42 UTC, mhauru commented on pyproject.toml
> +envlist = py37, py38, py39, py310, py311
Done

2023-08-03 09:57 UTC, mhauru commented
Tests fail on 3.12, but I made the other changes. Please edit the changelog entry to be to your liking.

2023-08-03 09:58 UTC, agronholm commented on .github/workflows/test.yml
> +        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
Greenlet 3.0.0a1 works with Python 3.12. I've worked around this in another project like this: https://github.com/agronholm/apscheduler/blob/master/pyproject.toml#L46

2023-08-03 10:24 UTC, agronholm approved these changes

2023-08-03 10:25 UTC, merged

2023-08-03 10:25 UTC, agronholm commented
Thanks a lot!

2023-08-03 10:34 UTC, mhauru commented
No problem, @rbuffat did all the actual work here. Do you plan to release this to pypi or do you want further changes before that?

2023-08-03 10:35 UTC, agronholm commented
I think I will first tinker with the test suite and then release to PyPI later this week.

2023-08-03 20:28 UTC, amacfie commented
I'm not getting the `nullable` parameter in the `mapped_column` calls when the column is `NOT NULL`

2023-08-03 20:29 UTC, agronholm commented
What are you getting exactly?

2023-08-03 21:46 UTC, amacfie commented
Nevermind I guess it's not necessary <https://docs.sqlalchemy.org/en/20/changelog/whatsnew_20.html#:~:text=All%20nullable%20parameters%20can%20be%20implied%20using%20Optional%5B%5D>

2023-08-24 09:04 UTC, mhauru commented
Hi @agronholm, sorry to keep pestering you, I know you have competing priorities. Is there anything I can do to help in getting the SQLAlchemy 2 support into a PyPi release? It would unblock a series of dependency upgrades for our project.

2023-08-24 20:49 UTC, agronholm commented
I wanted to fix a couple more bugs first, but looks like I didn't have the time. I've released v3.0.0rc3 now to unblock your upgrades.

2023-09-07 08:25 UTC, pang-thebasement commented
Hello:
Thanks a lot to all contributors. I wanted to test sqlacodegen on our database, but when I try to pip install tag 3.0.0rc3

`git checkout 3.0.0rc3`
`python3 -m pip install -U .`

I get an error like this:

        Defaulting to user installation because normal site-packages is not writeable
        Processing /home/myuser/extra/software/sqlacodegen
          Installing build dependencies ... done
          Getting requirements to build wheel ... done
          Installing backend dependencies ... done
          Preparing metadata (pyproject.toml) ... done
        Building wheels for collected packages: UNKNOWN
          Building wheel for UNKNOWN (pyproject.toml) ... done
          Created wheel for UNKNOWN: filename=UNKNOWN-3.0.0rc3-py3-none-any.whl size=1867 sha256=d4d18a167a8f7c8f5c6a2bb9d8703aee259487e55336fc1e475998db872a5a99
          Stored in directory: /tmp/pip-ephem-wheel-cache-pj6osbkb/wheels/c5/88/d7/6594ab3afff35313f447a11f0f0dfe560bffee6b30ace33111
        Successfully built UNKNOWN
        Installing collected packages: UNKNOWN
        Successfully installed UNKNOWN-3.0.0rc3

After which there is a python package actually called UNKNOWN, which I can uninstall with `python3 -m pip uninstall UNKNOWN`
Sorry I can't help. The `pyproject.toml` looks fine to me. I haven't really used that format :-/

2023-09-07 09:28 UTC, pang-thebasement commented
Thanks, that works! And it gave in a blink some nice looking python code! Genius!